image: golang:latest

stages:
  - build
  - release

compile:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - check-payload
  only:
    - tags
  tags:
    - docker
    - shared

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "Creating release"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
  tags:
    - docker
    - shared
