image: golang:latest

stages:
  - build
  - release

compile:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - check-payload
  only:
    - tags
  tags:
    - docker
    - shared

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release"
    - release-cli --insecure-https create --name 'Release $TAG' --tag-name '$TAG' 
  release:                          
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: "check-payload"
          url: 'https://gitlab.cee.redhat.com/rphillip/check-payload/cw/-/jobs/${GE_JOB_ID}/artifacts/file/check-payload'
  tags:
    - docker
    - shared
