# List of directories to ignore. This is a prefix match,
# i.e. everything under a matched directory is ignored.
filter_dirs = [
  "/lib/firmware",
  "/lib/modules",
  "/usr/lib/.build-id",
  "/usr/lib/firmware",
  "/usr/lib/grub",
  "/usr/lib/modules",
  "/usr/share/app-info",
  "/usr/share/doc",
  "/usr/share/fonts",
  "/usr/share/icons",
  "/usr/share/openshift",
  "/usr/src/plugins",
  "/rootfs",
  "/sysroot",
]

[[rpm.glibc-common.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/sbin/build-locale-archive" ]

[[rpm.glibc.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/sbin/ldconfig", "/sbin/ldconfig" ]

[[rpm.runc.ignore]]
error = "ErrGoMissingTag"
files = [ "/usr/bin/runc" ]

[[rpm.podman-catatonit.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/libexec/catatonit/catatonit" ]

[[rpm.containernetworking-plugins.ignore]]
error = "ErrGoMissingTag"
dirs = [ "/usr/libexec/cni" ]

[[payload.openshift-enterprise-pod-container.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/bin/pod" ]

[payload.operator-lifecycle-manager-container]
filter_files = [ "/usr/bin/cpb" ]
