# List of directories to ignore. This is a prefix match,
# i.e. everything under a matched directory is ignored.
filter_dirs = [
  "/lib/firmware",
  "/lib/modules",
  "/usr/lib/.build-id",
  "/usr/lib/firmware",
  "/usr/lib/grub",
  "/usr/lib/modules",
  "/usr/share/app-info",
  "/usr/share/doc",
  "/usr/share/fonts",
  "/usr/share/icons",
  "/usr/share/openshift",
  "/usr/src/plugins",
  "/rootfs",
  "/sysroot",
]

[[rpm.glibc-common.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/sbin/build-locale-archive" ]

[[rpm.glibc.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/sbin/ldconfig" ]

[[rpm.runc.ignore]]
error = "ErrGoMissingTag"
files = [ "/usr/bin/runc" ]

[[rpm.podman-catatonit.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/libexec/catatonit/catatonit" ]

[[rpm.containernetworking-plugins.ignore]]
error = "ErrGoMissingTag"
files = [
  "/usr/libexec/cni/bandwidth",
  "/usr/libexec/cni/bridge",
  "/usr/libexec/cni/dhcp",
  "/usr/libexec/cni/dummy",
  "/usr/libexec/cni/firewall",
  "/usr/libexec/cni/host-device",
  "/usr/libexec/cni/host-local",
  "/usr/libexec/cni/ipvlan",
  "/usr/libexec/cni/loopback",
  "/usr/libexec/cni/macvlan",
  "/usr/libexec/cni/portmap",
  "/usr/libexec/cni/ptp",
  "/usr/libexec/cni/sample",
  "/usr/libexec/cni/sbr",
  "/usr/libexec/cni/static",
  "/usr/libexec/cni/tuning",
  "/usr/libexec/cni/vlan",
  "/usr/libexec/cni/vrf",
]

[[payload.openshift-enterprise-pod-container.ignore]]
error = "ErrNotDynLinked"
files = [ "/usr/bin/pod" ]

[payload.operator-lifecycle-manager-container]
filter_files = [ "/usr/bin/cpb" ]
